apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves-test
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hintofbasil/ArgoCD-sync-waves-test.git'
    path: app_of_apps_chart
    targetRevision: HEAD
    helm:
      values: |
        delay: '40'
      version: v3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
