apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves-test-1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hintofbasil/ArgoCD-sync-waves-test.git'
    path: deploy_chart
    targetRevision: HEAD
    helm:
      values: |
        delay: {{ .Values.delay }}
        name: sync-waves-test-1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves-test-2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hintofbasil/ArgoCD-sync-waves-test.git'
    path: deploy_chart
    targetRevision: HEAD
    helm:
      values: |
        delay: {{ .Values.delay }}
        name: sync-waves-test-2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

